# Generated by Django 5.2.6 on 2026-06-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userhealthprofile",
            name="allergies",
            field=models.JSONField(default=list),
        ),
    ]
