# Generated by Django 5.2.6 on 2026-06-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredient_lines",
            field=models.TextField(blank=True, null=True),
        ),
    ]
